INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10001', '9001', 'Drive System', 'CONV-DS');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10002', '9001', 'Conveyor Belt Assembly', 'CONV-BELT');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10003', '9001', 'Roller Assembly', 'CONV-ROLL');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10004', '9001', 'Electrical Control Unit', 'CONV-ECU');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10005', '9002', 'Stator Assembly', 'MOT-STA');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10006', '9002', 'Rotor Assembly', 'MOT-ROT');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10007', '9002', 'Cooling Fan', 'MOT-FAN');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10008', '9002', 'Terminal Box', 'MOT-TBOX');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10009', '9003', 'Nozzle Assembly', 'FILL-NZ');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10010', '9003', 'Pneumatic Cylinder', 'FILL-PC');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10011', '9003', 'Drive Mechanism', 'FILL-DM');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10012', '9003', 'PLC Control Unit', 'FILL-PLC');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10013', '9003', 'Hopper Tank', 'FILL-HT');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10014', '9004', 'Label Dispenser', 'LAB-DISP');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10015', '9004', 'Drive Motor', 'LAB-MOT');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10016', '9004', 'Sensor System', 'LAB-SENS');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10017', '9004', 'Control Panel', 'LAB-CP');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10018', '9005', 'PLC Module', 'CP-PLC');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10019', '9005', 'Power Supply Unit', 'CP-PSU');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10020', '9005', 'Circuit Breakers', 'CP-CB');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10021', '9005', 'Relay Board', 'CP-RLY');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10022', '9006', 'Camera Module', 'CAM-MOD');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10023', '9006', 'Lighting Unit', 'CAM-LIGHT');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10024', '9006', 'Image Processor', 'CAM-IP');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10025', '9006', 'Mounting Frame', 'CAM-FR');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10026', '9007', 'Input Shaft', 'GB-IN');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10027', '9007', 'Gear Train', 'GB-GEAR');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10028', '9007', 'Lubrication System', 'GB-LUBE');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10029', '9007', 'Output Shaft', 'GB-OUT');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10030', '9012', 'Load Cell', 'WS-LC');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10031', '9012', 'Display Unit', 'WS-DIS');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10032', '9012', 'Control PCB', 'WS-PCB');
INSERT INTO equipment_element (element_id, equipment_id, element_name, ref_no) VALUES ('10033', '9012', 'Platform Assembly', 'WS-PLAT');
