INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30001', '10001', 'Drive Shaft', 'Inspect wear, replace if damaged', '18');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30002', '10001', 'Bearing Assembly', 'Replace if noisy or worn', '1');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30003', '10001', 'Coupling', 'Check alignment and tighten', '18');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30004', '10001', 'Mounting Bolt Set', 'Tighten if loose', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30005', '10002', 'Conveyor Belt', 'Replace if cracked', '2');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30006', '10002', 'Tension Roller', 'Inspect and lubricate', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30007', '10002', 'Tracking Sensor', 'Replace if faulty', '9');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30008', '10002', 'Support Frame', 'Inspect structural integrity', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30009', '10003', 'Idler Roller', 'Replace if damaged', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30010', '10003', 'Roller Bearing', 'Replace if noisy', '1');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30011', '10003', 'Shaft Pin', 'Inspect and replace if bent', '18');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30012', '10003', 'Mounting Bracket', 'Tighten or replace', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30013', '10004', 'Contactor', 'Replace if burnt', '8');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30014', '10004', 'Wiring Harness', 'Replace if insulation damaged', '20');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30015', '10004', 'Fuse Unit', 'Replace if blown', '8');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30016', '10004', 'Cooling Fan', 'Replace if not rotating', '15');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30017', '10005', 'Stator Coil', 'Replace if winding failure', '6');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30018', '10005', 'Insulation Kit', 'Replace if degraded', '3');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30019', '10005', 'Cooling Duct', 'Clean or replace', '15');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30020', '10005', 'Mounting Flange', 'Inspect cracks', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30021', '10006', 'Rotor Shaft', 'Replace if worn', '18');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30022', '10006', 'Rotor Bearing', 'Replace if noisy', '1');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30023', '10006', 'Balancing Weight', 'Inspect and secure', '18');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30024', '10006', 'End Cover', 'Replace if cracked', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30025', '10007', 'Fan Blade', 'Replace if broken', '15');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30026', '10007', 'Fan Guard', 'Tighten or replace', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30027', '10007', 'Mounting Bolt', 'Tighten', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30028', '10007', 'Air Duct', 'Clean', '15');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30029', '10008', 'Terminal Connector', 'Replace if loose', '20');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30030', '10008', 'Terminal Insulator', 'Replace if cracked', '20');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30031', '10008', 'Wiring Clamp', 'Replace if damaged', '20');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30032', '10008', 'Cable Gland', 'Replace if leaking', '20');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30033', '10009', 'Filling Nozzle', 'Replace if clogged', '11');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30034', '10009', 'Nozzle Seal', 'Replace if leaking', '3');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30035', '10009', 'Flow Sensor', 'Replace if faulty', '9');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30036', '10009', 'Mounting Clamp', 'Tighten', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30037', '10010', 'Pneumatic Cylinder', 'Replace if slow movement', '10');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30038', '10010', 'Seal Kit', 'Replace if leaking', '10');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30039', '10010', 'Piston Rod', 'Replace if bent', '18');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30040', '10010', 'Bracket', 'Tighten', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30041', '10011', 'Cam Disc', 'Replace if worn', '4');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30042', '10011', 'Drive Gear', 'Replace if damaged', '4');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30043', '10011', 'Lubrication Port', 'Lubricate', '5');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30044', '10011', 'Shaft Bearing', 'Replace if noisy', '1');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30045', '10012', 'PLC CPU', 'Replace if faulty', '6');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30046', '10012', 'I/O Module', 'Replace if not responding', '7');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30047', '10012', 'Relay Module', 'Replace if stuck', '17');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30048', '10012', 'Mounting Rail', 'Inspect stability', '19');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30049', '10013', 'Hopper Valve', 'Replace if leaking', '12');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30050', '10013', 'Valve Seal', 'Replace if worn', '3');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30051', '10013', 'Level Sensor', 'Replace if faulty', '9');
INSERT INTO equipment_parts (part_id, equipment_element_id, name, reaction_plan, spare_part_id) VALUES ('30052', '10013', 'Support Frame', 'Inspect integrity', '19');
