CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(100),
    industry VARCHAR(255),
    status VARCHAR(50),
    address TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE plants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT,
    code VARCHAR(100),
    name VARCHAR(255),
    location VARCHAR(255),
    timezone VARCHAR(100),
    status VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_plants_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id)
        ON DELETE CASCADE
);

CREATE TABLE departments (
    dept_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT,
    name VARCHAR(255),
    code VARCHAR(100),
    manager_user_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_departments_plant
        FOREIGN KEY (plant_id)
        REFERENCES plants(id)
        ON DELETE CASCADE
);

CREATE TABLE access_permissions (
    access_level_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_name VARCHAR(255),
    permissions JSONB,
    created_at TIMESTAMP
);

CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    access_level_id BIGINT,
    created_at TIMESTAMP,

    CONSTRAINT fk_roles_access_level
        FOREIGN KEY (access_level_id)
        REFERENCES access_permissions(access_level_id)
);

CREATE TABLE employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    password TEXT,
    full_name VARCHAR(255),
    role_id BIGINT,
    plant_id BIGINT,
    dept_id BIGINT,
    shift VARCHAR(50),
    expertise VARCHAR(255),
    performance_score NUMERIC,
    availability_score NUMERIC,
    active BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_employees_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id),

    CONSTRAINT fk_employees_plant
        FOREIGN KEY (plant_id)
        REFERENCES plants(id),

    CONSTRAINT fk_employees_department
        FOREIGN KEY (dept_id)
        REFERENCES departments(dept_id)
);

CREATE TABLE lines (
    line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT,
    dept_id BIGINT,
    line_name VARCHAR(255),
    line_code VARCHAR(100),
    supervisor_user_id BIGINT,
    line_manager_id BIGINT, -- Added column for Line Manager
    capacity_per_hour NUMERIC,
    status VARCHAR(50),
    block VARCHAR(100),
    zone VARCHAR(100),
    line_location_code VARCHAR(100),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_lines_plant
        FOREIGN KEY (plant_id)
        REFERENCES plants(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_lines_department
        FOREIGN KEY (dept_id)
        REFERENCES departments(dept_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_lines_supervisor
        FOREIGN KEY (supervisor_user_id)
        REFERENCES employees(employee_id),

    CONSTRAINT fk_lines_line_manager
        FOREIGN KEY (line_manager_id)
        REFERENCES employees(employee_id)
);

CREATE TABLE spare_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT,
    part_number VARCHAR(100),
    name VARCHAR(255),
    category VARCHAR(255),
    min_stock INTEGER,
    max_stock INTEGER,
    current_stock INTEGER,
    cost NUMERIC,
    location_in_sap VARCHAR(255),
    vendor_id BIGINT,
    created_at TIMESTAMP,

    CONSTRAINT fk_spare_company
        FOREIGN KEY (plant_id)
        REFERENCES plants(id)
        ON DELETE CASCADE
);

CREATE TABLE equipment_type (
    equipment_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP
);

CREATE TABLE equipments (
    equipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT,
    department_id BIGINT,
    line_id BIGINT,
    equipment_type_id BIGINT,
    name VARCHAR(255),
    code VARCHAR(100),
    qr_code VARCHAR(100),
    serial_number VARCHAR(100),
    manufacturer VARCHAR(255),
    model VARCHAR(255),
    installation_date DATE,
    criticality VARCHAR(50),
    bom JSONB,
    documentation_urls TEXT,
    equipment_location_detail TEXT,
    mounted_side VARCHAR(100),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,

    FOREIGN KEY (plant_id) REFERENCES plants(id),
    FOREIGN KEY (department_id) REFERENCES departments(dept_id),
    FOREIGN KEY (line_id) REFERENCES lines(line_id),
    FOREIGN KEY (equipment_type_id) REFERENCES equipment_type(equipment_type_id)
);

CREATE TABLE equipment_element (
    element_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT,
    element_name VARCHAR(255),
    ref_no VARCHAR(100),

    CONSTRAINT fk_element_equipment
        FOREIGN KEY (equipment_id)
        REFERENCES equipments(equipment_id)
        ON DELETE CASCADE
);

CREATE TABLE equipment_parts (
    part_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_element_id BIGINT,
    name VARCHAR(255),
    reaction_plan TEXT,
    spare_part_id BIGINT,

    CONSTRAINT fk_parts_element
        FOREIGN KEY (equipment_element_id)
        REFERENCES equipment_element(element_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_parts_spare
        FOREIGN KEY (spare_part_id)
        REFERENCES spare_parts(id)
);


CREATE TABLE pm_std_tasks (
    std_task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_ref_no VARCHAR(100),
    element_id BIGINT,
    part_id BIGINT,
    task_criticality VARCHAR(50),
    maintenance_strategy VARCHAR(100),
    method TEXT,
    tool TEXT,
    assignee_role_id BIGINT,
    estimated_req_time INTEGER,
    mode VARCHAR(50),
    frequency VARCHAR(100),
    standard_value NUMERIC,
    tolerance_min NUMERIC,
    tolerance_max NUMERIC,
    uom VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_updated_by BIGINT,

    FOREIGN KEY (element_id) REFERENCES equipment_element(element_id),
    FOREIGN KEY (part_id) REFERENCES equipment_parts(part_id),
    FOREIGN KEY (assignee_role_id) REFERENCES roles(role_id)
);

CREATE TABLE pm_task_schedules (
    task_schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    std_task_id BIGINT,
    last_schedule_date DATE,
    next_schedule_date DATE,
    is_active BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_updated_by BIGINT,

    FOREIGN KEY (std_task_id) REFERENCES pm_std_tasks(std_task_id)
);

CREATE TABLE pm_schedule_execution (
    schedule_execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_schedule_id BIGINT,
    employee_id BIGINT,
    assigned_dttm TIMESTAMP,
    due_date TIMESTAMP,
    status VARCHAR(50),
    completed_dttm TIMESTAMP,
    time_taken NUMERIC,
    actual_value NUMERIC,
    deviation_flag BOOLEAN,
    reschedule_flag BOOLEAN,
    notes TEXT,

    FOREIGN KEY (task_schedule_id)
        REFERENCES pm_task_schedules(task_schedule_id)
        ON DELETE CASCADE,

    FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id)
);

CREATE TABLE pm_schedule_approval (
    execution_approval_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_execution_id BIGINT,
    approval_level INTEGER,
    approver_id BIGINT,
    approval_status VARCHAR(50),
    approval_due_date TIMESTAMP,
    approved_dttm TIMESTAMP,
    remarks TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    FOREIGN KEY (schedule_execution_id)
        REFERENCES pm_schedule_execution(schedule_execution_id)
        ON DELETE CASCADE,

    FOREIGN KEY (approver_id)
        REFERENCES employees(employee_id)
);
