-- ========================================================================
-- PHM ANALYTICS SCHEMA MIGRATION
-- Tables for Predictive Maintenance Dashboards & Insights
-- ========================================================================

-- ------------------------------------------------------------------------
-- TABLE 1: phm_health_scores
-- Unified table for tracking top-down health metrics across the hierarchy
-- ------------------------------------------------------------------------
CREATE TABLE phm_health_scores (
    health_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_date DATE NOT NULL,
    entity_type VARCHAR(50) NOT NULL,    -- e.g., 'PLANT', 'DEPARTMENT', 'LINE', 'EQUIPMENT'
    entity_id BIGINT NOT NULL,           -- The ID of the respective plant, dept, or line
    health_score NUMERIC(5,2),           -- 0 to 100.00
    critical_flags_count INTEGER DEFAULT 0,
    pm_compliance_rate NUMERIC(5,2),     -- 0 to 100.00
    employee_efficiency NUMERIC(5,2),    -- 0 to 100.00
    task_rejection_rate NUMERIC(5,2),    -- 0 to 100.00
    approval_turnaround_time VARCHAR(50), -- e.g., '1d 4h'
    evidence_compliance_rate NUMERIC(5,2),  -- 0 to 100.00

    trend VARCHAR(20),                   -- 'IMPROVING', 'STABLE', 'DEGRADING'
    window_days INTEGER DEFAULT 365,     -- Number of days in the rolling window
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast daily dashboard loading
CREATE INDEX idx_phm_health_lookup ON phm_health_scores(entity_type, entity_id, evaluation_date, window_days);


-- ------------------------------------------------------------------------
-- TABLE 2: phm_degradation_predictions
-- Stores the mathematical outputs from the Python engine's nightly runs
-- ------------------------------------------------------------------------
CREATE TABLE phm_degradation_predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id BIGINT NOT NULL,
    task_schedule_id BIGINT,             -- Links to the specific PM schedule driving this data
    evaluation_date DATE NOT NULL,
    current_value NUMERIC,               -- The last logged reading
    predicted_failure_date DATE,         -- The mathematically projected failure date
    confidence_score NUMERIC(5,2),       -- Based on historical cycle variance
    days_remaining INTEGER,         
    degradation_velocity NUMERIC,        -- The rate of change (slope)
    risk_score NUMERIC(5,2),             -- Normalized 0-100 risk factor
    lifecycle_ratio NUMERIC(5,4),        -- e.g., 0.8500 (85% through expected life)
    chart_data_payload JSONB,            -- JSON array for plotting charts on UI
    is_active BOOLEAN DEFAULT TRUE,      -- Set to FALSE when part is eventually replaced
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pred_part 
        FOREIGN KEY (part_id) 
        REFERENCES equipment_parts(part_id) 
        ON DELETE CASCADE
);

-- Index to quickly find the active prediction for a specific part
CREATE INDEX idx_phm_active_predictions ON phm_degradation_predictions(part_id) WHERE is_active = TRUE;


-- ------------------------------------------------------------------------
-- TABLE 3: phm_action_insights
-- The Notification/Action queue for Line and Maintenance Managers
-- ------------------------------------------------------------------------
CREATE TABLE phm_action_insights (
    insight_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id BIGINT,                      -- For Line Manager filtering
    part_id BIGINT,                      -- The specific part failing
    insight_type VARCHAR(50),            -- e.g., 'PREDICTIVE_WARNING', 'ANOMALY_DETECTED'
    insight_code VARCHAR(100) NOT NULL,  -- Unique frontend localization key (e.g., 'VIBRATION_SPIKE_WARNING')
    severity VARCHAR(50),                -- 'CRITICAL', 'WARNING', 'INFO'
    metadata JSONB,                      -- Dynamic UI data (e.g., {"velocity": 0.4, "predicted_fail": "2026-10-06"})
    status VARCHAR(50) DEFAULT 'UNREAD', -- 'UNREAD', 'ACKNOWLEDGED', 'ACTION_TAKEN'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_insight_line 
        FOREIGN KEY (line_id) 
        REFERENCES lines(line_id) 
        ON DELETE CASCADE,

    CONSTRAINT fk_insight_part 
        FOREIGN KEY (part_id) 
        REFERENCES equipment_parts(part_id) 
        ON DELETE CASCADE
);

-- Index for fetching a manager's unread notifications instantly
CREATE INDEX idx_phm_unread_insights ON phm_action_insights(line_id, status);


-- ========================================================================
-- SYSTEM JOB MANAGEMENT SCHEMA
-- Tables for orchestrating and auditing background tasks and cron jobs
-- ========================================================================

-- ------------------------------------------------------------------------
-- TABLE 1: system_jobs
-- The registry of available background tasks
-- ------------------------------------------------------------------------
CREATE TABLE system_jobs (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_code VARCHAR(100) UNIQUE NOT NULL,      -- e.g., 'NIGHTLY_PHM_ANALYTICS_SYNC'
    job_name VARCHAR(255) NOT NULL,             -- e.g., 'Nightly Predictive Maintenance Analytics Sync'
    description TEXT,
    target_api_endpoint VARCHAR(255),           -- The microservice URL this job hits (e.g., '/api/v1/analytics/run-nightly')
    is_active BOOLEAN DEFAULT TRUE,
    cron_expression VARCHAR(100),               -- e.g., '0 0 2 * * ?' (2 AM daily)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------
-- TABLE 2: job_execution_history
-- The audit log of every job run (Cron or Manual)
-- ------------------------------------------------------------------------
CREATE TABLE job_execution_history (
    execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    triggered_by_employee_id BIGINT,            -- NULL if triggered by system/cron. Populated if manual.
    trigger_type VARCHAR(50) NOT NULL,          -- 'CRON', 'MANUAL_UI', 'MANUAL_API'
    status VARCHAR(50) NOT NULL,                -- 'IN_PROGRESS', 'COMPLETED_SUCCESS', 'FAILED', 'TIMED_OUT'
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    duration_ms BIGINT,                         -- How long the job took to run
    response_payload JSONB,                     -- The JSON response from the microservice (for debugging)
    error_message TEXT,                         -- Stack trace or error note if FAILED
    
    CONSTRAINT fk_execution_job 
        FOREIGN KEY (job_id) 
        REFERENCES system_jobs(job_id) 
        ON DELETE CASCADE,

    CONSTRAINT fk_execution_employee 
        FOREIGN KEY (triggered_by_employee_id) 
        REFERENCES employees(employee_id) 
        ON DELETE SET NULL
);

-- Index for quickly loading the "Job History" dashboard
CREATE INDEX idx_job_history_lookup ON job_execution_history(job_id, status, started_at DESC);


-- ========================================================================
-- SEED DATA: Registering the Analytics Job
-- ========================================================================

INSERT INTO system_jobs (job_code, job_name, description, target_api_endpoint, cron_expression) 
VALUES (
    'NIGHTLY_PHM_ANALYTICS_SYNC', 
    'Nightly Predictive Analytics Batch', 
    'Triggers the Python microservice to recalculate all machine degradation curves and generate new action insights.', 
    'http://analytics-service:8000/api/v1/batch/run-nightly?window_days=365', 
    '0 0 2 * * ?' -- Runs at 2:00 AM daily
);

INSERT INTO system_jobs (job_code, job_name, description, target_api_endpoint, cron_expression)
VALUES (
    'SHORT_TERM_PHM_ANALYTICS_SYNC', 
    'Short Term Predictive Analytics Sync', 
    'Triggers the Python microservice to recalculate short term compliance metrics (30 days window).', 
    'http://analytics-service:8000/api/v1/batch/run-nightly?window_days=30', 
    '0 30 2 * * ?' -- Runs at 2:30 AM daily
);


CREATE TABLE phm_evaluation_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT,
    evaluation_date DATE NOT NULL,
    plant_id BIGINT,
    department_id BIGINT,
    line_id BIGINT,
    equipment_id BIGINT,
    part_id BIGINT,
    task_schedule_id BIGINT,
    std_task_id BIGINT,
    evaluation_status VARCHAR(50) NOT NULL,
    reason_code VARCHAR(100),
    data_points_count INTEGER DEFAULT 0,
    current_cycle_points_count INTEGER DEFAULT 0,
    completed_cycles_count INTEGER DEFAULT 0,
    current_value NUMERIC,
    risk_score NUMERIC(5,2),
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_eval_audit_execution
        FOREIGN KEY (execution_id)
        REFERENCES job_execution_history(execution_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_eval_audit_part
        FOREIGN KEY (part_id)
        REFERENCES equipment_parts(part_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_phm_eval_audit_execution ON phm_evaluation_audit(execution_id);
CREATE INDEX idx_phm_eval_audit_lookup ON phm_evaluation_audit(evaluation_date, evaluation_status, part_id);