CREATE TABLE system_job_schedules (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    schedule_code VARCHAR(100) UNIQUE NOT NULL,
    schedule_name VARCHAR(255) NOT NULL,
    quartz_job_name VARCHAR(150) NOT NULL,
    quartz_job_group VARCHAR(150) NOT NULL DEFAULT 'SYSTEM_JOBS',
    quartz_trigger_name VARCHAR(150) NOT NULL,
    quartz_trigger_group VARCHAR(150) NOT NULL DEFAULT 'SYSTEM_JOB_TRIGGERS',
    cron_expression VARCHAR(100) NOT NULL,
    time_zone VARCHAR(100) NOT NULL DEFAULT 'Asia/Kolkata',
    is_active BOOLEAN DEFAULT TRUE,
    misfire_policy VARCHAR(50) DEFAULT 'DO_NOTHING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_system_job_schedule_job
        FOREIGN KEY (job_id)
        REFERENCES system_jobs(job_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_system_job_schedules_job ON system_job_schedules(job_id, is_active);

INSERT INTO system_job_schedules (
    job_id,
    schedule_code,
    schedule_name,
    quartz_job_name,
    quartz_job_group,
    quartz_trigger_name,
    quartz_trigger_group,
    cron_expression,
    time_zone,
    is_active,
    misfire_policy
)
SELECT
    job_id,
    'NIGHTLY_PHM_ANALYTICS_SYNC_SCHEDULE',
    'Nightly PHM Analytics Quartz Schedule',
    'NIGHTLY_PHM_ANALYTICS_SYNC_JOB',
    'ANALYTICS',
    'NIGHTLY_PHM_ANALYTICS_SYNC_TRIGGER',
    'ANALYTICS',
    COALESCE(cron_expression, '0 0 2 * * ?'),
    'Asia/Kolkata',
    TRUE,
    'DO_NOTHING'
FROM system_jobs
WHERE job_code = 'NIGHTLY_PHM_ANALYTICS_SYNC'
ON CONFLICT (schedule_code) DO NOTHING;
