-- ──────────────────────────────────────────────────────────────
-- V27: CONFIG_PARAM — central store for all tunable business params
-- ──────────────────────────────────────────────────────────────

CREATE TABLE config_param (
    param_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param_key    VARCHAR(100) NOT NULL,
    param_value  VARCHAR(500) NOT NULL,
    param_category VARCHAR(100) NOT NULL,
    description  TEXT,
    data_type    VARCHAR(20)  NOT NULL DEFAULT 'STRING',  -- STRING | INTEGER | LONG | DOUBLE | BOOLEAN
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_config_param_key UNIQUE (param_key),
    CONSTRAINT chk_config_param_data_type
        CHECK (data_type IN ('STRING', 'INTEGER', 'LONG', 'DOUBLE', 'BOOLEAN'))
);

CREATE INDEX idx_config_param_category ON config_param (param_category);
CREATE INDEX idx_config_param_active   ON config_param (is_active);

-- ──────────────────────────────────────────────────────────────
-- Seed: WORKFLOW category
-- Controls approval due-date calculation in ApprovalWorkflowService
-- ──────────────────────────────────────────────────────────────
INSERT INTO config_param (param_key, param_value, param_category, data_type, description) VALUES
('APPROVAL_DUE_DATE_OFFSET_DAYS',
 '1',
 'WORKFLOW',
 'LONG',
 'Days added to "now" when an approval row transitions to APPROVAL_REQUESTED status. Controls how long the next approver has before the task is considered overdue.'),

('RESCHEDULE_DUE_DATE_OFFSET_DAYS',
 '1',
 'WORKFLOW',
 'LONG',
 'Days after a rejection event to set the due date of the newly rescheduled task execution assigned back to the operator.');

-- ──────────────────────────────────────────────────────────────
-- Seed: ISSUE_FLAG category
-- Controls auto-calculated due dates for flags by criticality level
-- (used in IssueFlagService when no explicit due date is provided)
-- ──────────────────────────────────────────────────────────────
INSERT INTO config_param (param_key, param_value, param_category, data_type, description) VALUES
('FLAG_DUE_DATE_CRITICAL_DAYS',
 '1',
 'ISSUE_FLAG',
 'INTEGER',
 'Days from now to set the auto-calculated due date when a CRITICAL criticality issue flag is escalated without an explicit due date.'),

('FLAG_DUE_DATE_HIGH_DAYS',
 '1',
 'ISSUE_FLAG',
 'INTEGER',
 'Days from now to set the auto-calculated due date when a HIGH criticality issue flag is escalated without an explicit due date.'),

('FLAG_DUE_DATE_MEDIUM_DAYS',
 '2',
 'ISSUE_FLAG',
 'INTEGER',
 'Days from now to set the auto-calculated due date when a MEDIUM criticality issue flag is escalated without an explicit due date.'),

('FLAG_DUE_DATE_LOW_DAYS',
 '7',
 'ISSUE_FLAG',
 'INTEGER',
 'Days from now to set the auto-calculated due date when a LOW (or unrecognised) criticality issue flag is escalated without an explicit due date.');

-- ──────────────────────────────────────────────────────────────
-- Seed: TASK category
-- Controls QR-scan duplicate-execution guard in TaskExecutionService
-- ──────────────────────────────────────────────────────────────
INSERT INTO config_param (param_key, param_value, param_category, data_type, description) VALUES
('TASK_RECENT_COMPLETION_THRESHOLD_DAYS',
 '7',
 'TASK',
 'LONG',
 'When an operator scans a QR code, if the same task execution was completed within this many days the API returns status "recently_completed" and blocks a duplicate submission. Prevents accidental double-execution of periodic PM tasks.');

-- ──────────────────────────────────────────────────────────────
-- Seed: S3 category
-- Controls presigned URL expiry durations in AwsS3Service
-- (bucket names and AWS credentials stay in application.properties)
-- ──────────────────────────────────────────────────────────────
INSERT INTO config_param (param_key, param_value, param_category, data_type, description) VALUES
('S3_GET_URL_EXPIRY_MINUTES',
 '15',
 'S3',
 'LONG',
 'Validity window (minutes) for presigned S3 GET URLs generated for reading task observation images and documents.'),

('S3_PUT_URL_EXPIRY_MINUTES',
 '15',
 'S3',
 'LONG',
 'Validity window (minutes) for presigned S3 PUT URLs generated so the mobile app can upload observation photos and flag replacement images directly to S3.');

-- ──────────────────────────────────────────────────────────────
-- Seed: ANALYTICS category
-- Analytics engine tuning parameters — previously split across
-- Python env vars (config.py) and hardcoded constants in
-- predictor.py / evaluator.py / insights.py
-- ──────────────────────────────────────────────────────────────
INSERT INTO config_param (param_key, param_value, param_category, data_type, description) VALUES
('ANALYTICS_WARN_THRESHOLD_RATIO',
 '0.875',
 'ANALYTICS',
 'DOUBLE',
 'Fraction of the max tolerance threshold at which a PREDICTIVE_WARNING insight is generated. E.g. 0.875 means warn at 87.5% of max tolerance.'),

('ANALYTICS_STABLE_SLOPE_EPSILON',
 '0.002',
 'ANALYTICS',
 'DOUBLE',
 'Absolute slope magnitude (per day) below which a degradation trend is classified as STABLE rather than progressing toward failure.'),

('ANALYTICS_ANOMALY_VELOCITY_RATIO',
 '1.3',
 'ANALYTICS',
 'DOUBLE',
 'Ratio of current degradation velocity to historical average above which a DEGRADATION_ANOMALY insight is raised (e.g. 1.3 = 30% faster than normal).'),

('ANALYTICS_WINDOW_DAYS',
 '365',
 'ANALYTICS',
 'INTEGER',
 'Historical data window (days) passed to both the nightly and short-term analytics runs when evaluating health scores.'),

('ANALYTICS_CRITICAL_RISK_THRESHOLD',
 '90',
 'ANALYTICS',
 'DOUBLE',
 'Risk score (0–100) above which an evaluated part/task is counted as a "critical flag" when computing entity-level health scores.'),

('ANALYTICS_TREND_STABILITY_THRESHOLD',
 '1.0',
 'ANALYTICS',
 'DOUBLE',
 'Maximum absolute delta between the new health score and the previous one for the trend to be classified as STABLE. Deltas above this are IMPROVING or DEGRADING.'),

('ANALYTICS_HEALTH_CONFIG_MISSING_SCORE',
 '60.0',
 'ANALYTICS',
 'DOUBLE',
 'Health contribution score assigned to a part/task whose evaluation_status is CONFIG_MISSING (no tolerance thresholds defined).'),

('ANALYTICS_HEALTH_INSUFFICIENT_DATA_SCORE',
 '70.0',
 'ANALYTICS',
 'DOUBLE',
 'Health contribution score assigned to a part/task whose evaluation_status is INSUFFICIENT_DATA (fewer than two completed readings).'),

('ANALYTICS_HEALTH_NO_RISK_FALLBACK_SCORE',
 '75.0',
 'ANALYTICS',
 'DOUBLE',
 'Health contribution fallback score used when a prediction exists but risk_score is null (should not happen under normal flow).'),

('ANALYTICS_MIN_CONFIDENCE_SCORE',
 '60.0',
 'ANALYTICS',
 'DOUBLE',
 'Floor value for the calculated prediction confidence score. Prevents confidence from being reported below this level regardless of cycle variance.'),

('ANALYTICS_MAX_CONFIDENCE_SCORE',
 '95.0',
 'ANALYTICS',
 'DOUBLE',
 'Ceiling value for the calculated prediction confidence score. Prevents overconfident predictions even with very consistent historical cycles.'),

('ANALYTICS_LR_CONFIDENCE_CAP',
 '55.0',
 'ANALYTICS',
 'DOUBLE',
 'When the prediction method is LINEAR_REGRESSION (only one completed prior cycle), the confidence score is capped at this value to reflect lower reliability.');
